export const GET_CART_REQUEST="GET_CART_REQUEST"
export const GET_CART_SUCSESS="GET_CART_SUCSESS"
export const GET_CART_FAILURE="GET_CART_FAILURE"

export const CART_POST_REQUEST="CART_POST_REQUEST"
export const CART_POST_SUCCESS="CART_POST_SUCCESS"
export const CART_POST_FAILURE="CART_POST_FAILURE"

export const CART_DELETE_REQUEST="CART_DELETE_REQUEST"
export const CART_DELETE_SUCCESS="CART_DELETE_SUCCESS"
export const CART_DELETE_FAILURE="CART_DELETE_FAILURE"

export const CART_PATCH_REQUEST="CART_PATCH_REQUEST"
export const CART_PATCH_SUCCESS="CART_PATCH_SUCCESS"
export const CART_PATCH_FAILURE="CART_PATCH_FAILURE"