export const SIGNUP_POST_REQUEST="SIGNUP_POST_REQUEST";
export const SIGNUP_POST_SUCCESS="SIGNUP_POST_SUCCESS";
export const SIGNUP_POST_FAILURE="SIGNUP_POST_FAILURE";


//login
export const LOGIN_POST_REQUEST="LOGIN_POST_REQUEST"
export const LOGIN_POST_SUCCESS="LOGIN_POST_SUCCESS"
export const LOGIN_POST_FAILURE="LOGIN_POST_FAILURE"

export const LOGOUT_REQUEST="LOGOUT_REQUEST"